$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %O %S';
$bibtex_use = 2;
$biber = 'biber %O %B';
$out_dir = 'build';
$aux_dir = 'build';
$clean_ext = 'bbl bcf blg run.xml synctex.gz';
